# -*- coding: utf-8 -*-
"""Class 1 - Starting in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hFBBwKr1IpPTl-SK0vzKEkTqnb4eEIi
"""

# my first code
# printing "Hello, World!"
print('Hello, World!')

# my second code
# instantiating two variables - "firstName" and "lastName"
firstName = 'fernando'
lastName = 'galvão'

# concatenating the variables, "firstName" and "lastName" into a new variable "fullName"
fullName = firstName + ' ' + lastName

# printing your presentation (full name) and using the "title" function.
# it aims to make the first letter capitalized.
print(f'My name is {fullName.title()}.')

"""Now, we will load a database - excel file - but for this it is necessary to first import the library `"pandas"`. For this, we use the command `"import pandas as pd"`.
  - **Notes:** `"pd"` is an abbreviation of the library's name and is widely used by the community.
"""

# importing the necessary library
import pandas as pd

# loading the database into the variable "sales_abacates"
sales_abacates = pd.read_excel('controle_de_abacates.xlsx')

# viewing the first 10 lines of the file
sales_abacates.head(10)

# general information
sales_abacates.info()

# statistic data
sales_abacates.describe().T

"""Now let's perform some visual analysis with the file"""

# plotting a graph - data X preco_medio
sales_abacates.plot('data', 'preco_medio');

# plotting a graph - data X volume_total
sales_abacates.plot('data', 'volume_total');

